name: Backup Repository

on:
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"   # runs every 2 minutes automatically

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history for backup

      # Step 2: Create backup archive
      - name: Create backup archive
        run: |
          mkdir -p backup
          tar -czf backup/time-tracker-$(date +%F-%H%M).tar.gz .

      # Step 3: Upload backup artifact
      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-backup
          path: backup/*.tar.gz

      # Step 4: Optional post-action / cleanup
      - name: Cleanup Workspace
        if: always()
        run: |
          echo "Backup workflow finished."
