name: Maven Build Java App

on:
  workflow_dispatch:
  push:
      branches: [main]
  pull_request:
      branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      
      - name: Build with Maven 
        run: mvn -B -DskipTests clean install
      
      - name: Cleanup Workspace
        if: always()
        run: |
          echo "Pipeline Finished."
          rm -rf *

